# This workflow will build a .NET project
name: .NET

on:
  push:
    branches: [ "YaropudVova-patch-1" ]
  pull_request:
    branches: [ "YaropudVova-patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      run: dotnet publish -c Release -o publish
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: publish/**
