name: CI

on: 
  push:
    branches: [master]

jobs: 
  build: 
    runs-on: [windows]

    steps:
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v2.0.0
      - name: restore-nuget-packages
        run: nuget restore TeamChallenge.sln
      - name: Build the solution
        run: msbuid TeamChallenge.sln
        
